name: misoca_flutter
description: Misoca sample client

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0

environment:
  sdk: '>=3.0.0-233.0.dev <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  decimal: ^2.3.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_constraintlayout: ^1.6.3-stable
  flutter_pdfview: ^1.3.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.1
  freezed_annotation: ^2.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.0
  logger: ^1.3.0
  path_provider: ^2.0.14
  retrofit: ^4.0.1
  share_plus: ^6.3.4
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.1
  flutter_gen: ^5.3.0
  flutter_gen_runner: ^5.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    - assets/images/

# FlutterGenライブラリが使用する設定
# https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  # FlutterGenで使用したい機能を有効化する
  integrations:
    flutter_svg: true
